@extends('adminlte::page')

@section('title', 'Saved Transactions')

@section('content_header')
    <div class="d-flex justify-content-between align-items-center mb-2">
        <h1 class="text-white">Saved Transactions</h1>
        <div class="mb-3">
                <button id="btnAuthenticateOICP" class="btn btn-primary btn-sm">
                    <i class="fas fa-shield-alt"></i> Batch OICP
                </button>
                <button id="btnBatchAuthenticate" class="btn btn-success btn-sm">
                    <i class="fas fa-file-excel"></i> Batch ISAP
                </button>
            </div>
    </div>

<style>
    /* Dark Theme Core Adjustments */
    .card { background-color: #343a40; color: #fff; border: 1px solid #4b545c; }
    .table { color: #fff !important; }
    
    .card-body { 
        padding: 1rem; 
        overflow: hidden; 
    }

    /* Table Header - Sticky Fix for internal scroll */
    #transTable thead th { 
        vertical-align: middle; 
        background-color: #454d55 !important; 
        color: #fff;
        border-bottom: 2px solid #4b545c;
        font-weight: 600 !important; 
        position: sticky;
        top: 0;
        z-index: 10;
    }

    /* FIX: Ensure the header checkbox is visible and styled correctly */
    #transTable thead th input[type="checkbox"] {
        cursor: pointer;
        z-index: 20;
        position: relative;
    }

    /* Global unbold for cells, bold only for COC numbers */
    #transTable tbody td, 
    #transTable tbody td span:not(.coc-red) { font-weight: 400 !important; }

    #transTable .action-buttons i {
        font-weight: 900 !important;
        display: inline-block !important;
        visibility: visible !important;
    }

    #transTable td {
        vertical-align: middle !important;
        height: 50px; 
        border-top: 1px solid #4b545c;
    }

    .dataTables_info, .dataTables_length, .dataTables_filter { color: #fff !important; }
    .page-link { background-color: #454d55; border-color: #6c757d; color: #fff; }
    
    .truncate {
        max-width: 180px; 
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    input[type="checkbox"] {
        transform: scale(1.1);
        filter: invert(100%) hue-rotate(180deg) brightness(1.5);
    }

    .dataTables_scrollHead th:first-child input[type="checkbox"] {
        margin: 0 auto;
        display: block;
        transform: scale(1.2);
        filter: invert(100%) hue-rotate(180deg) brightness(1.5);
    }

    .dataTables_scrollHeadInner {
        width: 100% !important;
    }
    /* --- THEMED SCROLLBARS --- */
    /* This targets the vertical and horizontal scroll areas generated by DataTables */
    .dataTables_scrollBody::-webkit-scrollbar {
        width: 10px;  /* Vertical width */
        height: 10px; /* Horizontal height */
    }

    .dataTables_scrollBody::-webkit-scrollbar-track {
        background: #2c3136; /* Slightly darker than the card for contrast */
        border-radius: 4px;
    }

    .dataTables_scrollBody::-webkit-scrollbar-thumb {
        background: #6c757d; /* Muted gray for the handle */
        border-radius: 4px;
        border: 2px solid #2c3136; /* Creates a "floating" effect */
    }

    .dataTables_scrollBody::-webkit-scrollbar-thumb:hover {
        background: #495057; /* Darker gray on hover */
    }

    /* Fix for the corner piece where horizontal and vertical scrollbars meet */
    .dataTables_scrollBody::-webkit-scrollbar-corner {
        background: #2c3136;
    }

    /* Ensure the sticky header stays aligned with the themed background */
    .dataTables_scrollHead {
        background-color: #343a40 !important;
        border-bottom: 2px solid #4b545c !important;
    }
</style>
@stop

@section('content')
    <div class="card card-outline card-primary shadow">
        <div class="card-body">
            @php
            $heads = [
                // FIX: Add the "Select All" checkbox HTML into the label
                ['label' => '', 'no-export' => true, 'width' => '1%'], 
                ['label' => 'Agent', 'width' => '12%'],
                ['label' => 'Assured', 'width' => '23%'],
                ['label' => 'COC No', 'width' => '10%'],
                ['label' => 'Plate No.', 'width' => '10%'],
                ['label' => 'Denomination', 'width' => '15%'],
                ['label' => 'Date & Time', 'width' => '15%'],
                ['label' => 'Action', 'no-export' => true, 'width' => '8%']
            ];

            $config = [
                'processing' => true,
                'serverSide' => true,
                'ajax' => route('admin.saved_transactions'),
                'columns' => [
                    ['data' => 'checkbox', 'name' => 'checkbox', 'orderable' => false, 'className' => 'text-center'],
                    ['data' => 'agent', 'name' => 'agent', 'className' => 'truncate'],
                    ['data' => 'vehicle.assured', 'name' => 'vehicle.assured', 'className' => 'truncate'],
                    ['data' => 'coc_no', 'name' => 'coc_no', 'className' => ''],
                    ['data' => 'vehicle.plate_no', 'name' => 'vehicle.plate_no'],
                    ['data' => 'vehicle.denomination', 'name' => 'vehicle.denomination'],
                    ['data' => 'created_at', 'name' => 'created_at'],
                    ['data' => 'action', 'name' => 'action', 'orderable' => false, 'className' => 'text-center action-buttons'],
                ],
                'order' => [[6, 'desc']],
                'autoWidth' => false,
                'lengthMenu' => [ [10, 50, 100, 500, 1000], [10, 50, 100, 500, 1000] ],
                'pageLength' => 10,
                'responsive' => false, 
                'scrollX' => true,      // Horizontal scrolling enabled
                'scrollY' => '55vh',    // Vertical height set to 55% of viewport
                'scrollCollapse' => true, // Shrinks the container if data is short
            ];
            @endphp

            <x-adminlte-datatable id="transTable" :heads="$heads" :config="$config" 
                class="text-nowrap" striped hoverable bordered compressed theme="dark" />
        </div>
    </div>
@stop

@section('js')
<script src="https://cdn.jsdelivr.net/npm/xlsx/dist/xlsx.full.min.js"></script>
<script>
$(document).ready(function() {
    // 1. Initialize Table Reference
    var table = $('#transTable').DataTable();

    /**
     * SCROLL FIX: Injects the "Select All" checkbox into the correct header.
     * When scrollY is enabled, DataTables creates a separate div for the header.
     * This listener ensures the checkbox is re-inserted every time the table redraws.
     **/
    table.on('draw', function() {
        $('.dataTables_scrollHead th:first-child').html('<input type="checkbox" id="selectAll" style="cursor:pointer;">');
    });

    // 2. Initial animation for the card
    $('.card').hide().fadeIn(800);

    // 3. Helper function to clean data for Excel
    function clean(value, removeAllSpaces = false) {
        if (!value) return '';
        let cleaned = value.toString()
            .replace(/<[^>]*>?/gm, '') 
            .replace(/,/g, '') 
            .trim();
        if (removeAllSpaces) {
            cleaned = cleaned.replace(/\s+/g, ''); 
        }
        return cleaned;
    }

    /**
     * SELECT ALL LOGIC 
     * Uses delegated events so it works even after the header is redrawn.
     **/
    $(document).on('click', '#selectAll', function() {
        // Find all checkboxes in the current view/filtered result
        var rows = table.rows({ 'search': 'applied' }).nodes();
        $('input.row-checkbox', rows).prop('checked', this.checked);
    });

    // Update "Select All" status if a single row is unchecked
    $(document).on('change', '.row-checkbox', function() {
        if (!this.checked) {
            $('#selectAll').prop('checked', false);
        } else {
            // If all checkboxes are checked, check the selectAll box
            var total = $('.row-checkbox').length;
            var checked = $('.row-checkbox:checked').length;
            if(total === checked) {
                $('#selectAll').prop('checked', true);
            }
        }
    });

    // 4. Batch Authenticate Logic
    $('#btnBatchAuthenticate').on('click', function() {
        // Targets all checked row-checkboxes in the table body
        const checked = $('#transTable tbody .row-checkbox:checked');
        
        if (checked.length === 0) {
            Swal.fire({
                icon: 'info',
                title: 'No Selection',
                text: 'Please select rows to generate the ISAP CSV.',
                background: '#343a40',
                color: '#fff'
            });
            return;
        }

        let excelData = [
            ["ISAP","ISAP","","","","","","","","","","",""],
            ["COC_NO","PLATE_NO","MV FILE_NO","MOTOR_NO","CHASSIS_NO","INCE_DATE","EXPI_DATE","PREM_TYPE","REG_TYPE","TAX_TYPE","ASSURED NAME","ASSURED TIN","MV_TYPE"]
        ];

        checked.each(function() {
            const rowData = table.row($(this).closest('tr')).data();
            if (!rowData) return;
            
            // Format COC (Example: Adding prefix 010)
            let rawCOC = clean(rowData.coc_no, true);
            let formattedCOC = "010" + rawCOC;

            // Date Formatting Logic
            let dateStr = clean(rowData.created_at).split('|')[0].trim();
            let inceDateObj = new Date(dateStr);
            
            // Format: MM/DD/YYYY
            let inceDate = ((inceDateObj.getMonth()+1)+'').padStart(2,'0') + '/' +
                           (inceDateObj.getDate()+'').padStart(2,'0') + '/' +
                           inceDateObj.getFullYear();

            // Set Expiry to +1 Year
            let expiDateObj = new Date(inceDateObj);
            expiDateObj.setFullYear(expiDateObj.getFullYear() + 1);

            let expiDate = ((expiDateObj.getMonth()+1)+'').padStart(2,'0') + '/' +
                           (expiDateObj.getDate()+'').padStart(2,'0') + '/' +
                           expiDateObj.getFullYear();

            // Vehicle Denomination Mapping
            let denom = clean(rowData.vehicle.denomination).toUpperCase();
            let mvType = "";
            let premType = "1";

            if (["CAR", "SEDAN", "PASSENGER CAR", "COUPE", "HATCHBACK"].includes(denom)) mvType = "C";
            else if (denom === "UTILITY VEHICLE") mvType = "UV";
            else if (denom === "SUV") mvType = "SV";
            else if (denom === "MC") mvType = "M";
            else if (denom === "MTC") mvType = "MS";
            else if (denom === "TRICYCLE") mvType = "TC";
            else if (denom === "TRUCK") mvType = "TK";
            else if (denom === "TRAILER") mvType = "TL";
            else mvType = denom;

            // Premium Type Logic
            if (mvType === "C" || mvType === "SV" || mvType === "UV") premType = "1";
            else if (mvType === "TK") premType = "3";
            else if (["M","MS","TC","TL"].includes(mvType)) premType = "7";

            excelData.push([
                formattedCOC,
                clean(rowData.vehicle.plate_no, true),
                clean(rowData.vehicle.file_no, true),
                clean(rowData.vehicle.engine_no, true),
                clean(rowData.vehicle.chassis_no, true),
                inceDate,
                expiDate,
                premType,
                "R", // Reg Type
                "0", // Tax Type
                clean(rowData.vehicle.assured),
                "111-111-111-11111", // Default TIN
                mvType
            ]);
        });

        // 5. Generate and Download Excel
        let wb = XLSX.utils.book_new();
        let ws = XLSX.utils.aoa_to_sheet(excelData);
        XLSX.utils.book_append_sheet(wb, ws, "ISAP Upload");
        XLSX.writeFile(wb, "ISAP_Upload_" + new Date().getTime() + ".xlsx");
    });

    // 5. Authenticate OICP Logic
    $('#btnAuthenticateOICP').on('click', function() {
        const checked = $('#transTable tbody .row-checkbox:checked');
        
        if (checked.length === 0) {
            Swal.fire({
                icon: 'info',
                title: 'No Selection',
                text: 'Please select rows to generate the OICP Template.',
                background: '#343a40',
                color: '#fff'
            });
            return;
        }

        // Define Header based on your provided column list
        let oicpData = [
            [
                "Transaction Type", "Authentication Type", "Car Type", "Serial/Chassis No", 
                "Motor No./Engine No.", "Plate No", "MV file Number", "Assured Name", 
                "Assured Address", "Mobile Number", "Email Address", "O.R Number", 
                "COC Number", "Policy Number", "Assured TIN", "Inception Date", 
                "Expiration Date To", "Vehicle Type", "LTO MV Type", "LTO Branch", 
                "Series/Model", "Vehicle Make", "Year", "Body Type", "Color", 
                "Unladen Weight / GVW (KG)", "Authorized Capacity (KG)"
            ]
        ];

        checked.each(function() {
            const rowData = table.row($(this).closest('tr')).data();
            if (!rowData) return;

            // 1. Vehicle Type (OICP Category) Mapping Logic
            let denom = clean(rowData.vehicle.denomination).toUpperCase();
            let oicpVehicleType = "Private Car"; // Default fallback

            if (["CAR", "UTILITY VEHICLE", "SEDAN", "SUV", "HATCHBACK", "COUPE", "PASSENGER CAR"].includes(denom)) {
                oicpVehicleType = "Private Car";
            } else if (denom.includes("TRUCK")) {
                oicpVehicleType = "Heavy Trucks";
            } else if (["MC", "MTC", "TRICYCLE"].includes(denom)) {
                oicpVehicleType = "Motorcycles/Tricycles, Trailers";
            }

            // 2. NEW: LTO MV Type Mapping Logic
            let ltoMvType = "";
            if (denom === "SUV") {
                ltoMvType = "SV";
            } else if (denom === "UTILITY VEHICLE") {
                ltoMvType = "UV";
            } else if (["CAR", "SEDAN", "HATCHBACK", "COUPE", "PASSENGER"].some(type => denom.includes(type))) {
                ltoMvType = "C";
            } else if (denom.includes("TRUCK")) {
                ltoMvType = "TK";
            } else if (denom === "MC") {
                ltoMvType = "M";
            } else if (denom === "MTC") {
                ltoMvType = "MS";
            } else if (denom === "TRICYCLE") {
                ltoMvType = "TC";
            } else {
                ltoMvType = denom; // Fallback to original if no match
            }

            // 2. Date Processing (Updated to YYYY-DD-MM)
            let dateStr = clean(rowData.created_at).split('|')[0].trim();
            let inceDateObj = new Date(dateStr);
            
            // Format: YYYY-DD-MM
            let inceDate = inceDateObj.getFullYear() + '-' +
                           (inceDateObj.getDate() + '').padStart(2, '0') + '-' +
                           ((inceDateObj.getMonth() + 1) + '').padStart(2, '0');

            let expiDateObj = new Date(inceDateObj);
            expiDateObj.setFullYear(expiDateObj.getFullYear() + 1);
            
            // Format: YYYY-DD-MM
            let expiDate = expiDateObj.getFullYear() + '-' +
                           (expiDateObj.getDate() + '').padStart(2, '0') + '-' +
                           ((expiDateObj.getMonth() + 1) + '').padStart(2, '0');

            // 3. Row Mapping
            oicpData.push([
                "RENEW",                          // Transaction Type
                "Manual",                         // Authentication Type
                "Vehicle",                        // Car Type
                clean(rowData.vehicle.chassis_no, true),
                clean(rowData.vehicle.engine_no, true),
                clean(rowData.vehicle.plate_no, true),
                clean(rowData.vehicle.file_no, true),
                clean(rowData.vehicle.assured),
                clean(rowData.vehicle.address || "N/A"), 
                "09209167801",                    // Mobile
                "TESS_ALPHA1@GMAIL.COM",          // Email
                "-",                              // O.R Number
                clean(rowData.coc_no, true),
                clean(rowData.policy_no || ""),   // Policy Number
                "11111111111",                    // Assured TIN
                inceDate,
                expiDate,
                oicpVehicleType,                  // Mapping result from step 1
                ltoMvType,                               // LTO MV Type
                "-",                               // LTO Branch
                clean(rowData.vehicle.series || ""), 
                clean(rowData.vehicle.make || ""),   
                clean(rowData.vehicle.year_model || ""),   
                clean(rowData.vehicle.denomination || ""), 
                clean(rowData.vehicle.color || ""),     
                clean(rowData.vehicle.gross_weight || "0"), 
                clean(rowData.vehicle.capacity || "0")
            ]);
        });

        // Generate Excel
        let wb = XLSX.utils.book_new();
        let ws = XLSX.utils.aoa_to_sheet(oicpData);
        XLSX.utils.book_append_sheet(wb, ws, "OICP Template");
        XLSX.writeFile(wb, "OICP_Authenticate_" + new Date().getTime() + ".xlsx");
    });
});
</script>
@stop